version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: todo-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/todo
      - JWT_SECRET=sekretny_klucz_rozwojowy
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  # Frontend aplikacja React  
  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # Baza danych MongoDB
  mongo:
    image: mongo:6.0
    container_name: todo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
